### ISSUE TITLE
dual images

### ISSUE THREAD

**Issue by fmburns** [Loper-House/Loper-House.github.io#6]
I would like to be able to post an image of a plant and its location(s) in the yard side-by-side.  I have used tables in html to complete this task, but I am not sure how github would do it.  Urgent? Not really...at the moment.

**Comment by rebecca-burwei** [comment]
Hi Francis - give this a try. The code below makes a table with two columns. 

```
| Caption 1 | Caption 2 |
| ---       | ---       |
| ![alternate text for image 1](url for image 1) | ![alternate text for image 2](url for image 2) |
```

More specifically, the first line of the code makes the table header. The second line of code makes separates the header from the rest of the table. The third line makes a row in the table with two images.

**Comment by fmburns** [comment]
Thanks!

**Comment by rebecca-burwei** [comment]
Hi Francis - I saw you tried to add this to example.md . I fixed it so you should see a table on the example page now. There was just some trickiness with the whitespace.

**Comment by fmburns** [comment]
Rebecca
Great, thanks! I have enjoyed my efforts.
Francis

**Comment by fmburns** [comment]
I agree.
